### ISSUE TITLE
Error: "Cannot close a loan with less than the market's minValue"

### ISSUE THREAD

**Issue by D-Biela** [Liqwid-Labs/liqwid-liquidation-bot#1]
I have created a wallet via cardano-cli as specified in the docs and funded it with 150+ ADA.

When running the container i'm getting the following error:

```
[INFO] 2023-04-14T12:25:13.516Z (runLiquidationProcess) Liquidating next highest position
[ERROR] 2023-04-14T12:25:14.318Z (runLiquidationProcess) Could not liquidate loan given by:
(TransactionInput { index: 1u, transactionId: (TransactionHash (hexToByteArrayUnsafe "4e4738d2e520f08a1334542cfc17b25a085eac76d1ef1ad499b6d80f012f9624")) })
Error raised was:
Error: Cannot close a loan with less than the market's minValue
    at exports.error (webpack-internal:///885:6374:12)
    at eval (webpack-internal:///885:68029:366)
    at eval (webpack-internal:///885:10414:36)
    at eval (webpack-internal:///885:6701:32)
    at eval (webpack-internal:///885:3134:26)
    at eval (webpack-internal:///885:10414:36)
    at run (webpack-internal:///885:9465:24)
    at eval (webpack-internal:///885:9535:21)
    at drain (webpack-internal:///885:9307:11)
    at Object.enqueue (webpack-internal:///885:9328:13)
Trying next highest position.
```

This is my current config (docker-compose):

```
version: "3.4"
services:

  Liqwid-ADA-Liquidation-Bot:
    image: ghcr.io/liqwid-labs/liqwid-liquidation-bot:staging
    restart: always
    environment:
      - SKEY=...
      - INTERVAL=3
      - MARKET=Ada
      - VERBOSE=false
```

I have tried runnning the mainnet- & staging-tag.

Any idea whats wrong?

**Comment by 4TT1L4** [comment]
> funded it with 150+ ADA
I was actually wondering how much funds are needed in the wallet to operate a mainnet bot.

I understand that the loans can be partially liquidated, but I am still not really sure how much funds should be in the wallet.

Is there any recommendation about this? Some rule of thumb? It would be nice to see this in the documentation as well.

The documentation states in a note that the wallet must be funded, but I could not find any further information about this.
