### ISSUE TITLE
Configuration: Turn off coloring in the output

### ISSUE THREAD

**Issue by 4TT1L4** [Liqwid-Labs/liqwid-liquidation-bot#3]
**Problem:**
 - The color codes are not picked up by the GCP Logs Explorer (Cloud Platform Specific Log Aggregator Service)

**Proposed Solution:**
 - Provide a way to disable color in the output of the liquidation bot.

**Resources:**

Screenshot:

![image](https://user-images.githubusercontent.com/2914096/234230012-752e2d67-703d-4a13-8044-9ca3ab06719b.png)

**Comment by t1lde** [comment]
> **Problem:**
> 
>     * The color codes are not picked up by the GCP Logs Explorer (Cloud Platform Specific Log Aggregator Service)
> 
> 
> **Proposed Solution:**
> 
>     * Provide a way to disable color in the output of the liquidation bot.
> 
> 
> **Resources:**
> 
> Screenshot:
> 
> ![image](https://user-images.githubusercontent.com/2914096/234230012-752e2d67-703d-4a13-8044-9ca3ab06719b.png)

If you add a line

```
PLAIN_LOG=yes
```

In the liquidationBotEnv, it will enable plain logs.

I will make a TODO to document all of the env options.

**Comment by 4TT1L4** [comment]
Thank you for the hint about the `PLAIN_LOG` configuration setting.

After setting this environment variable to `yes`, the color codes do not appear anymore, but the logs got very verbose.

Is there a way to keep the logs non-verbose (like before), but have no color codes in the output? 

Do I need to set `VERBOSE` explicitly to `false`?

```
VERBOSE=false
```

Thanks for the help.

**Comment by 4TT1L4** [comment]
Based on [a recent discussion on Discord](https://discord.com/channels/759807412688388136/1080239097139961906/1100411743324340318), @t1lde has confirmed:

> The VERBOSE setting is not really working as expected. 

This must be addressed to make PLAIN_LOG work properly.

At the moment it is changing the format of the log entries, but also increases the verbosity to "debug" / "troubleshooting" level.

This is not necessary for normal operation.

**Comment by dfar-sga** [comment]
Should be fixed with `LOGGER=NoColourLogger`.
